### PR TITLE
Add functions for deciphering MS TGTs

### PR DESCRIPTION
**Pull request by dmulder**
(Refers|Fixes) #

## Checklist

- [x] This pr contains no AI generated code
- [x] cargo fmt has been run
- [x] cargo clippy has been run and there's no issues
- [ ] cargo test has been run and passes

### CODE REVIEW

**Comment by dmulder** [comment]
I wrote this months ago and forgot about it. It's necessary for decrypting the TGTs returned by MS Azure.

**Comment by dmulder** [comment]
Oh, goodness, now it's failing because some versions of clippy don't recognize `manual_inspect`. @Firstyear do you have any ideas?

**Comment by dmulder** [comment]
I don't actually need any of this. Sorry for the noise.

**Comment by Firstyear** [comment]
@dmulder What version of rust were you using? That can cause some clippy confusion. Could also be CI here in this project needs an update maybe? 

Anyway, don't be sorry :) no harm done at all :)

**Comment by dmulder** [comment]
> @dmulder What version of rust were you using? That can cause some clippy confusion. Could also be CI here in this project needs an update maybe?
> 
> Anyway, don't be sorry :) no harm done at all :)

It was actually the CI here. Clippy demanded the change (via CI), then the build failed (again in CI) when I implemented it. Lol

**Comment by Firstyear** [comment]
@yaleman Do we need to update something here for our CI to avoid this? I suspect we have an older rust version here somewhere.

**Comment by yaleman** [comment]
Yes the automation calls 1.70 specifically https://github.com/kanidm/hsm-crypto/blob/main/.github/workflows/ci.yml#L35

**Comment by Firstyear** [comment]
@yaleman Can I leave it to you to update this once you return?

**Pull request closed without merging**
