### PR TITLE
Progress on MS extension support

### PR DESCRIPTION
**Pull request by Firstyear**
Add support for MS OAPXBC key management in the soft-tpm, with a view to have this work with HW TPM's. 

## Checklist

- [ x ] This pr contains no AI generated code
- [ x ] cargo fmt has been run
- [ x ] cargo clippy has been run and there's no issues
- [ x ] cargo test has been run and passes

### CODE REVIEW

**Comment by dmulder** [comment]
Lgtm

**Review by dmulder — APPROVED** [review]

**Comment by dmulder** [comment]
@Firstyear I don't have rights to merge, so you'll need to push the button yourself.

**Comment by dmulder** [comment]
FYI, I'm using your sealing code to prevent the release of the PRT:
https://github.com/himmelblau-idm/microsoft-authentication-library-for-rust/commit/45a383e3fa9399c1913d6211acb41dc9bbdd3afe
Technically a client with the TPM secrets could decrypt it, but I'm not enabling it. This way the PRT is a black box, that can be stashed in a database, then retrieved and passed to msal for authenticating later.

**Comment by Firstyear** [comment]
@dmulder I don't know how I overlooked that, I gave you maintainer access now.

**Pull request merged**
